#this version of yaml
apiVersion: apps/v1
#the type of Kubernetes resource we are using
#a deployment is when we run code on a server
kind: Deployment
#metadata is info related to the object we created in Kubernetes
metadata:
  #the name here is the name of the deployment
  name: stedi-logan-shuman
spec:
  #Replicas refers to the number of pods we deploy
  replicas: 1
  #A selector is a route to my pod
  selector:
    #These are labels for my selector
    matchLabels:
    #App is a specific kind of label for my pod
      app: stedi-logan-shuman
  #The template describes all the features of my pod
  template:
    #metadata provides labels for my template
    metadata:
      labels:
        app: stedi-logan-shuman
  #the spec refers to the specification of my containers in my pod
    spec:
    #the containers can have one or more Docker containers in the pod
      containers:
        #the name of the container is specified below:
          - name: stedi-logan-shuman
            image: gcr.io/cit262-group-project/stedi-logan-shuman
#the ports is a list of tcp ports the pod listens on
            ports:
             - containerPort: 4567
#resources are the compute resources used by the pod in the cloud
            resources:
#Limits represent the max amount of cpu and memory allowed for the pod
              limits:
#CPU is the max amount of CPU that can be used by the pod
                cpu: ".125"
#Memory is the max amount of memory that can be used by the pod
                memory: "500Mi"
#Requests is the minimum amount of compute resources used by the pod
              requests:
#CPU is the minimum amount of CPU the pod needs to run
                cpu: ".125"
#Memory is the minimum amount of memory the pod needs to run
                memory: "250Mi"
#LivenessProbe is a configuration that checks the pod for health
            livenessProbe:
#HttpGet instructs kubernetes to do an http request to check health
             httpGet:
#Path defines the url to use when doing the HTTP request
                path: /
#Port defines the port to use when doing the HTTP request
                port: 4567
#initialDelaySeconds tells Kubernetes to wait before doing a request
             initialDelaySeconds: 10
#periodSeconds tells Kubernetes how often to check health
             periodSeconds: 3

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stedi-ingress-logan
  annotations:
    kubernetes.io/ingress.global-static-ip-name: stedi-public-logan
    networking.gke.io/managed-certificates: stedi-certificate-logan
    kubernetes.io/ingress.allow-http: "false"
    # the below line wasn't there before
    kubernetes.io/ingress.class: "gce"
spec:
# the below lines were here before

#  backend:
#    serviceName: stedi-nodeport
#    servicePort: 80

# the below lines weren't there before
  defaultBackend:
    service:
      name: stedi-nodeport-logan
      port:
        number: 80
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: stedi-certificate-logan
spec:
  domains:
    - loganshuman.cit262.com
---
apiVersion: v1
kind: Service
metadata:
  name: stedi-nodeport-logan
spec:
  selector:
    app: stedi-logan-shuman
  type: NodePort
  ports:
    - port: 80
      targetPort: 4567



